[package]
name = "log2vcd"
version = "0.1.0"
authors = ["Atlas <achille@heraud.xyz>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
vcd = "0.4.0"
chrono = "0.4.6"
regex = "1.0.5"
lazy_static = "1.1.0"
